import { z } from "zod";
export declare const businessDetailsSchema: z.ZodEffects<z.ZodObject<{
    account_purpose: z.ZodEnum<["Business expenses", "Payroll", "Receive funds from clients"]>;
    selected_products: z.ZodArray<z.ZodEnum<["SEPA", "SEPA instant"]>, "many">;
    selected_currencies: z.ZodArray<z.ZodEnum<["GBP", "USD", "AED"]>, "many">;
    business_activity: z.ZodString;
    employees_count: z.ZodEnum<["1-10", "11-50", "51-200"]>;
    company_trading_name: z.ZodString;
    company_website: z.ZodString;
    country_of_operation: z.ZodString;
    no_office_additional_info: z.ZodOptional<z.ZodString>;
    initial_funds: z.ZodNumber;
    initial_source: z.ZodEnum<["Client funds", "UBO contribution", "Loans"]>;
    regulatory_requirement: z.ZodBoolean;
}, "strip", z.ZodTypeAny, {
    account_purpose: "Business expenses" | "Payroll" | "Receive funds from clients";
    selected_products: ("SEPA" | "SEPA instant")[];
    selected_currencies: ("GBP" | "USD" | "AED")[];
    business_activity: string;
    employees_count: "1-10" | "11-50" | "51-200";
    company_trading_name: string;
    company_website: string;
    country_of_operation: string;
    initial_funds: number;
    initial_source: "Client funds" | "UBO contribution" | "Loans";
    regulatory_requirement: boolean;
    no_office_additional_info?: string | undefined;
}, {
    account_purpose: "Business expenses" | "Payroll" | "Receive funds from clients";
    selected_products: ("SEPA" | "SEPA instant")[];
    selected_currencies: ("GBP" | "USD" | "AED")[];
    business_activity: string;
    employees_count: "1-10" | "11-50" | "51-200";
    company_trading_name: string;
    company_website: string;
    country_of_operation: string;
    initial_funds: number;
    initial_source: "Client funds" | "UBO contribution" | "Loans";
    regulatory_requirement: boolean;
    no_office_additional_info?: string | undefined;
}>, {
    account_purpose: "Business expenses" | "Payroll" | "Receive funds from clients";
    selected_products: ("SEPA" | "SEPA instant")[];
    selected_currencies: ("GBP" | "USD" | "AED")[];
    business_activity: string;
    employees_count: "1-10" | "11-50" | "51-200";
    company_trading_name: string;
    company_website: string;
    country_of_operation: string;
    initial_funds: number;
    initial_source: "Client funds" | "UBO contribution" | "Loans";
    regulatory_requirement: boolean;
    no_office_additional_info?: string | undefined;
}, {
    account_purpose: "Business expenses" | "Payroll" | "Receive funds from clients";
    selected_products: ("SEPA" | "SEPA instant")[];
    selected_currencies: ("GBP" | "USD" | "AED")[];
    business_activity: string;
    employees_count: "1-10" | "11-50" | "51-200";
    company_trading_name: string;
    company_website: string;
    country_of_operation: string;
    initial_funds: number;
    initial_source: "Client funds" | "UBO contribution" | "Loans";
    regulatory_requirement: boolean;
    no_office_additional_info?: string | undefined;
}>;
export type BusinessDetails = z.infer<typeof businessDetailsSchema>;
