name: Release Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version number"
        required: true
        default: "1.0.0"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - name: Set Version Manually
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version
      - name: Commit and Push Version Change
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add package.json # Add other modified files as needed
          git commit -m "chore(release): bump version to ${{ github.event.inputs.version }}"
          git push origin HEAD:main
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
