name: Release Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version number"
        required: true
        default: "1.0.0"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - name: Get changed files
        uses: tj-actions/changed-files@v44.4.0
        id: changed-files
      - run: npm install
      - name: Set Version Manually
        run: npm version ${{ github.event.inputs.version }}
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump collect-validation-schemas version to ${{ github.event.inputs.version }}
          branch: main
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
      - run: npm run build
      - name: Auto Commit Schema Version Bump
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump schemas version to ${{ github.event.inputs.version }}
          branch: main
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
